language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t dalpengholic/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dalpengholic/react-test npm run test   

after_success:
    - docker build -t dalpengholic/multi-client ./client
    - docker build -t dalpengholic/multi-nginx ./nginx
    - docker build -t dalpengholic/multi-server ./server
    - docker build -t dalpengholic/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push dalpengholic/multi-client
    - docker push dalpengholic/multi-nginx
    - docker push dalpengholic/multi-server
    - docker push dalpengholic/multi-worker